name = "podcast"
account_id = "9f59889bd7648271ab70330290195c0c"
compatibility_date = "2025-04-20"
workers_dev = true

main = "dist/index.js"

[build]
command = "npm run build"

[site]
bucket = "./dist/public"
